copyright = "Ross AKA RevolverRossalot AKA Rossalot AKA Six-Sided Vice"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/London"
timeout = "120s"
title = "Six-Sided Vice"

[params]
  defaultTheme = "dark"
  description = "These are my favourite plastic children. Please do not tell the others, though."
  title = "Ross' hobby gallery"
  logo = "logo.png"
  [params.author]
    #email = "user@example.com"
    name = "Rossalot"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/rossalotminis/"
    #github = "https://github.com/nicokaiser/hugo-theme-gallery/"
    youtube = "https://www.youtube.com/@SixSidedVice"
    #email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    #name = "GitHub"
    #url = #"https://github.com/nicokaiser/hugo-theme-gallery/"
    #weight = 3

[services]
  [services.rss]
    limit = 100
